name: errorhandling
on: [push, pull_request]

jobs:
  msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v1
        with:
          msystem: MINGW64
          update: true
      - name: CI-Build
        shell: msys2 {0}
        run: |
          false;
          echo "ok";

  msys2-e:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v1
        with:
          msystem: MINGW64
          update: true
      - name: CI-Build
        shell: msys2 -e {0}
        run: |
          false;
          echo "ok";

  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-Build
        run: |
          false;
          echo "ok";